'use strict';
const express=require('express');
const fs=require('fs/promises');
const path=require('path');
const bcrypt=require('bcrypt');
const db=require('../config/db');
const catalog=require('../services/catalogService');
const admin=require('../services/adminService');
const {requireAdmin}=require('../middleware/auth');
const upload=require('../middleware/upload');
const router=express.Router();
router.use(requireAdmin);

router.get('/',async(_req,res,next)=>{try{const {rows}=await db.query(`SELECT (SELECT count(*) FROM books) books,(SELECT count(*) FROM users) users,(SELECT count(*) FROM authors) authors,(SELECT count(*) FROM concepts) concepts`);res.render('admin/dashboard',{title:'Administración',stats:rows[0]});}catch(e){next(e);}});

router.get('/books',async(req,res,next)=>{try{res.render('admin/books/index',{title:'Libros',books:await catalog.listBooks(String(req.query.q||'')),q:String(req.query.q||'')});}catch(e){next(e);}});
router.get('/books/new',async(_req,res,next)=>{try{res.render('admin/books/form',{title:'Nuevo libro',book:null,...await admin.options()});}catch(e){next(e);}});
router.post('/books',async(req,res,next)=>{try{const id=await admin.saveBook(null,req.body);req.session.success='Libro creado.';res.redirect(`/admin/books/${id}/edit`);}catch(e){handleDb(e,req,res,next,'/admin/books/new');}});
router.get('/books/:id/edit',async(req,res,next)=>{try{const book=await catalog.getBook(req.params.id);if(!book)return res.sendStatus(404);res.render('admin/books/form',{title:'Editar libro',book,...await admin.options()});}catch(e){next(e);}});
router.put('/books/:id',async(req,res,next)=>{try{await admin.saveBook(req.params.id,req.body);req.session.success='Libro actualizado.';res.redirect(`/admin/books/${req.params.id}/edit`);}catch(e){handleDb(e,req,res,next,`/admin/books/${req.params.id}/edit`);}});
router.delete('/books/:id',async(req,res,next)=>{try{await db.query('DELETE FROM books WHERE id=$1',[req.params.id]);req.session.success='Libro eliminado.';res.redirect('/admin/books');}catch(e){next(e);}});

router.post('/books/:id/concepts',async(req,res,next)=>{try{const definition=String(req.body.definition||'').trim();if(definition.length<10){req.session.error='La definición debe contener al menos 10 caracteres.';return res.redirect(`/admin/books/${req.params.id}/edit`);}await db.query(`INSERT INTO book_concepts(book_id,concept_id,definition,chapter_reference,page_reference) VALUES($1,$2,$3,$4,$5) ON CONFLICT(book_id,concept_id) DO UPDATE SET definition=excluded.definition,chapter_reference=excluded.chapter_reference,page_reference=excluded.page_reference`,[req.params.id,req.body.concept_id,definition,String(req.body.chapter_reference||'').trim()||null,String(req.body.page_reference||'').trim()||null]);req.session.success='Definición guardada.';res.redirect(`/admin/books/${req.params.id}/edit`);}catch(e){next(e);}});
router.delete('/books/:bookId/concepts/:conceptId',async(req,res,next)=>{try{await db.query('DELETE FROM book_concepts WHERE book_id=$1 AND concept_id=$2',[req.params.bookId,req.params.conceptId]);res.redirect(`/admin/books/${req.params.bookId}/edit`);}catch(e){next(e);}});
router.post('/books/:id/images',upload.single('image'),async(req,res,next)=>{try{if(!req.file){req.session.error='Selecciona una imagen.';return res.redirect(`/admin/books/${req.params.id}/edit`);}await db.query('INSERT INTO book_images(book_id,file_path,alt_text,sort_order,is_primary) VALUES($1,$2,$3,$4,$5)',[req.params.id,`/uploads/${req.file.filename}`,String(req.body.alt_text||'').trim(),Number(req.body.sort_order||0),req.body.is_primary==='on']);req.session.success='Imagen cargada.';res.redirect(`/admin/books/${req.params.id}/edit`);}catch(e){if(req.file)await fs.unlink(req.file.path).catch(()=>{});next(e);}});
router.put('/books/:bookId/images/:imageId',async(req,res,next)=>{try{await db.query('UPDATE book_images SET alt_text=$1,sort_order=$2,is_primary=$3 WHERE id=$4 AND book_id=$5',[String(req.body.alt_text||'').trim(),Math.max(0,Number(req.body.sort_order||0)),req.body.is_primary==='on',req.params.imageId,req.params.bookId]);req.session.success='Metadatos de imagen actualizados.';res.redirect(`/admin/books/${req.params.bookId}/edit`);}catch(e){next(e);}});
router.delete('/books/:bookId/images/:imageId',async(req,res,next)=>{try{const {rows}=await db.query('DELETE FROM book_images WHERE id=$1 AND book_id=$2 RETURNING file_path',[req.params.imageId,req.params.bookId]);if(rows[0]&&rows[0].file_path.startsWith('/uploads/'))await fs.unlink(path.join(path.resolve(process.env.UPLOAD_DIR||'uploads'),path.basename(rows[0].file_path))).catch(()=>{});res.redirect(`/admin/books/${req.params.bookId}/edit`);}catch(e){next(e);}});

router.get('/masters/:resource',async(req,res,next)=>{try{const meta=admin.resource(req.params.resource);res.render('admin/masters/index',{title:req.params.resource,resource:req.params.resource,meta,rows:await admin.listMaster(req.params.resource)});}catch(e){next(e);}});
router.get('/masters/:resource/new',(req,res,next)=>{try{res.render('admin/masters/form',{title:'Nuevo registro',resource:req.params.resource,meta:admin.resource(req.params.resource),row:null});}catch(e){next(e);}});
router.post('/masters/:resource',async(req,res,next)=>{try{await admin.createMaster(req.params.resource,req.body);req.session.success='Registro creado.';res.redirect(`/admin/masters/${req.params.resource}`);}catch(e){handleDb(e,req,res,next,`/admin/masters/${req.params.resource}/new`);}});
router.get('/masters/:resource/:id/edit',async(req,res,next)=>{try{res.render('admin/masters/form',{title:'Editar registro',resource:req.params.resource,meta:admin.resource(req.params.resource),row:await admin.getMaster(req.params.resource,req.params.id)});}catch(e){next(e);}});
router.put('/masters/:resource/:id',async(req,res,next)=>{try{await admin.updateMaster(req.params.resource,req.params.id,req.body);req.session.success='Registro actualizado.';res.redirect(`/admin/masters/${req.params.resource}`);}catch(e){handleDb(e,req,res,next,`/admin/masters/${req.params.resource}/${req.params.id}/edit`);}});
router.delete('/masters/:resource/:id',async(req,res,next)=>{try{await admin.deleteMaster(req.params.resource,req.params.id);req.session.success='Registro eliminado.';res.redirect(`/admin/masters/${req.params.resource}`);}catch(e){handleDb(e,req,res,next,`/admin/masters/${req.params.resource}`);}});

router.get('/users',async(_req,res,next)=>{try{const {rows}=await db.query('SELECT id,name,email,role,active,created_at FROM users ORDER BY id');res.render('admin/users',{title:'Usuarios',users:rows});}catch(e){next(e);}});
router.post('/users',async(req,res,next)=>{try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)||password.length<8){const e=new Error('Nombre, correo o contraseña no cumplen la validación.');e.status=400;throw e;}const hash=await bcrypt.hash(password,12);await db.query('INSERT INTO users(name,email,password_hash,role,active) VALUES($1,$2,$3,$4,true)',[name,email,hash,req.body.role==='admin'?'admin':'user']);req.session.success='Usuario creado.';res.redirect('/admin/users');}catch(e){handleDb(e,req,res,next,'/admin/users');}});
router.put('/users/:id',async(req,res,next)=>{try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase();if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)){const e=new Error('Nombre o correo no cumplen la validación.');e.status=400;throw e;}await db.query('UPDATE users SET name=$1,email=$2,role=$3,active=$4 WHERE id=$5',[name,email,req.body.role==='admin'?'admin':'user',req.body.active==='on',req.params.id]);req.session.success='Usuario actualizado.';res.redirect('/admin/users');}catch(e){handleDb(e,req,res,next,'/admin/users');}});
router.delete('/users/:id',async(req,res,next)=>{try{if(Number(req.params.id)===req.session.user.id){req.session.error='No puedes eliminar tu propia cuenta activa.';return res.redirect('/admin/users');}await db.query('DELETE FROM users WHERE id=$1',[req.params.id]);res.redirect('/admin/users');}catch(e){handleDb(e,req,res,next,'/admin/users');}});

function handleDb(error,req,res,next,redirect){if(error.status===400){req.session.error=error.message;return res.redirect(redirect);}const safeMessages={23505:'Ya existe un registro con ese valor o la operación viola una regla de unicidad.',23503:'El registro está relacionado con otros datos y no puede modificarse o eliminarse de esa manera.',23514:'Uno de los valores no cumple las reglas permitidas.'};if(safeMessages[error.code]){console.error('Operación rechazada por PostgreSQL',error.code,error.constraint);req.session.error=safeMessages[error.code];return res.redirect(redirect);}next(error);}
module.exports=router;
